---
apiVersion: v1
kind: Service
metadata:
  namespace: <name>-<isu_num>
  name: lab0-jupyter-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8282
      name: jupyter
  selector:
    app: lab0-jupyter